sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - "pip install --upgrade pipenv"
  - "pipenv install --dev --skip-lock"
script:
  - "pipenv run nosetests"
  - "pipenv run flake8 zipstreamer"
  - "pipenv run pylint zipstreamer"
cache: pip
