__title__ = 'zipstreamer'
__description__ = 'Python library for generating ZIP files on-the-fly with ZIP file size information.'
__url__ = 'http://github.com/koofr/python-zipstreamer'
__version__ = '0.1.0'
__build__ = 0x000100
__author__ = 'Luka Zakrajsek'
__author_email__ = 'luka@bancek.net'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018 Koofr'
